### ISSUE TITLE
Provide feedback if the database can't be created

### ISSUE THREAD

**Issue by hastarin** [hastarin/HAST.Elite.Dangerous.DataAssistant#29]

**Comment by hastarin** [comment]
Any exception is now logged and a message is shown to the user asking them to submit the log.

Done as of 2e53e3086dd8bf9f51e23a3057657133c9f003fd

**Comment by stringandstickytape** [comment]
You might like to swipe the "create a dump file" code from RN to augment this, I've found that more useful and more reliable than any other form of user feedback on crash.  Again just an idea :)

**Comment by hastarin** [comment]
I considered it.  But I never have learnt how to analyze/read a dump file.  Catching the exception will do me.  ;)

**Comment by stringandstickytape** [comment]
It's surprisingly easy... make sure you have the right version of the software it was generated from, then File -> Open the dump file in Visual Studio, and hit "Debug Managed Code".  It puts you in the same debugger state that you'd have been in, if it had crashed locally - although you can't hit "Continue" sadly!  Worth messing about with if you have time :)

**Comment by hastarin** [comment]
Cool thanks.  I might just have to give that a go.
